#!/usr/bin/env python

# Copyright 2025 Chiizujin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys
import re

from pathlib import Path

FAMILIES = ('norn', 'grendel', 'ettin', 'geat')
SLOTS = 'abcdefghijklmnopqrstuvwxyz'
BODY_PARTS = '0abcdefghijklmnopqz'
SPECIES_GENDER = {'norn': ('0', '4'),
                  'grendel': ('1', '5'),
                  'ettin': ('2', '6'),
                  'geat': ('3', '7')}
LIFE_STAGE = '0123456'

def print_usage_and_exit():
    print('Usage: clearslot <family name> <slot>')
    sys.exit(1)

def print_invalid_dir_and_exit():
    print('This does not appear to be a Creatures 3 or Docking Station directory.')
    sys.exit(1)

def report_error_and_exit(e):
    print('An error occurred while deleting files:')
    print(e)
    sys.exit(1)

def delete_files(path, extension, species_gender, slot):
    pattern = f'[{BODY_PARTS}][{species_gender[0]}{species_gender[1]}][{LIFE_STAGE}][{slot}]'
    prog = re.compile(pattern)

    count = 0
    try:
        for file in path.glob(f'*.{extension}'):
            if re.search(prog, file.stem):
                count += 1
                file.unlink()
    except OSError as e:
        report_error_and_exit(e)

    return count

def main():
    if len(sys.argv) != 3:
        print_usage_and_exit()

    family_name = sys.argv[1].lower()
    slot = sys.argv[2].lower()
    if family_name not in FAMILIES or slot not in SLOTS:
        print_usage_and_exit()

    images_path = Path('Images')
    body_data_path = Path('Body Data')
    if not images_path.is_dir() or not body_data_path.is_dir():
        print_invalid_dir_and_exit()

    species_gender = SPECIES_GENDER[family_name]
    image_count = delete_files(images_path, '[cC]16', species_gender, slot)
    body_data_count = delete_files(body_data_path, '[aA][tT][tT]', species_gender, slot)

    if not image_count and not body_data_count:
        print(f'There is no breed in {family_name} slot {slot}.')
    else:
        print(f"Deleted {image_count} image{'' if image_count == 0 else 's'} and {body_data_count} body data file{'' if image_count == 0 else 's'}.")

if __name__ == '__main__':
    main()
